name: tilt
description: Easy access to the current tilt on `x` and `y` axis.
version: 0.0.3
repository: https://github.com/mia-recki/flutter-tilt

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^4.0.2
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: me.recki.tilt
        pluginClass: TiltPlugin
      ios:
        pluginClass: TiltPlugin
